### PR TITLE
Information Preparation for SKALE

### PR DESCRIPTION
**Pull request by vnessaDev**
Hello O3 Labs, 

Attached you'll find a JSON file with the values for a new asset request. 

Please let me know if you need anything else. 

Thank you kindly,
Vanessa Clarke
SKALE Labs

### CODE REVIEW

**Comment by AlexHiggins8** [comment]
Hi @vnessaDev , you need to correct the folder path with chain name and SKALE contract address(Checksum) instead. and the ID should also be a checksum address in JSON file. you can follow #2 to correct this PR.

**Comment by AlexHiggins8** [comment]
Hi @vnessaDev , you need to correct the folder path with chain name and SKALE contract address(Checksum) instead. and the ID should also be a checksum address in JSON file. you can follow #2 to correct this PR.

**Comment by vnessaDev** [comment]
Hello @AlexHiggins8. SKALE is a Layer-2 Ethereum sidechain network. I followed a similar pathway as, for example, Polygon.
Screen Shot 2022-06-14 at 2 26 50 PM

**Comment by AlexHiggins8** [comment]
@vnessaDev Hello, We can not get more informations about SKALE's `PUBLIC ENDPOINT` from your docs or on the [chainlist.org](https://chainlist.org/). BTW it's nice if you can offer some FAUCET/DApps for some test.

**Comment by vnessaDev** [comment]
Our faucet is launching soon, in about 2-3weeks. 

RPC Endpoints:
https://mainnet.skalenodes.com/v1/elated-tan-skat
wss://mainnet.skalenodes.com/v1/ws/elated-tan-skat

Chain ID:
0x79f99296

Block Explorer
https://elated-tan-skat.explorer.mainnet.skalenodes.com/

Thanks for all your help with this. @AlexHiggins8

**Comment by AlexHiggins8** [comment]
@vnessaDev  There are so many SKALE sidechain networks now, This does not comply with our existing rules. you can custom the network If you want to use it in O3 wallet.

**Pull request closed without merging**
